
CREATE DATABASE IF NOT EXISTS chat_db;

USE chat_db;

-- Tabela de Usuários
CREATE TABLE TB_USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NM_USUARIO VARCHAR(200) NOT NULL,
    DS_EMAIL VARCHAR(200) NOT NULL,
    DS_SENHA VARCHAR(20) NOT NULL,
    DT_CRIACAO DATETIME NOT NULL
);

-- Tabela de Salas
CREATE TABLE TB_SALA (
    ID_SALA INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    NM_SALA VARCHAR(200) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

-- Tabela de Mensagens
CREATE TABLE TB_MENSAGEM (
    ID_MENSAGEM INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO_ENVIO INT NOT NULL,
    ID_USUARIO_PARA INT NOT NULL,
    ID_SALA INT NOT NULL,
    DS_MENSAGEM VARCHAR(200) NOT NULL,
    DT_MENSAGEM DATETIME NOT NULL,
    FOREIGN KEY (ID_USUARIO_ENVIO) REFERENCES TB_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_USUARIO_PARA) REFERENCES TB_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_SALA) REFERENCES TB_SALA(ID_SALA)
);

-- Tabela de Participantes (relação muitos para muitos entre usuários e salas)
CREATE TABLE TB_PARTICIPANTE (
    ID_PARTICIPANTE INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_SALA INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_SALA) REFERENCES TB_SALA(ID_SALA)
);
